  # Copyright 2021-2025 The OpenSSL Project Authors. All Rights Reserved.
  #
  # Licensed under the Apache License 2.0 (the "License").  You may not use
  # this file except in compliance with the License.  You can obtain a copy
  # in the file LICENSE in the source distribution or at
  # https://www.openssl.org/source/license.html

  name: BoringSSL tests

  on: [pull_request]

  # for some reason, this does not work:
  # variables:
  #   BUILDOPTS: "-j4"
  #   HARNESS_JOBS: "${HARNESS_JOBS:-4}"

  # for some reason, this does not work:
  # before_script:
  #     - make="make -s"

  permissions:
    contents: read

  env:
    OSSL_RUN_CI_TESTS: 1

  jobs:
    external-tests-boringssl:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: config
          run: CXXFLAGS="-std=c++17" ./config --strict-warnings --banner=Configured --debug no-afalgeng enable-weak-ssl-ciphers enable-zlib enable-ec_nistp_64_gcc_128 enable-external-tests no-fips enable-ech enable-trace && perl configdata.pm --dump
        - name: make
          run: make -s -j4
        - name: get cpu info
          run: |
            cat /proc/cpuinfo
            ./util/opensslwrap.sh version -c
        - name: test external boringssl
          run: VERBOSE=1 BORING_RUNNER_DIR=$(pwd)/boringssl/ssl/test/runner make test TESTS="test_external_boringssl"
